[project]
name = "wi2012-automation"
dynamic = ["version"]
dependencies = [
    "python-docx==1.2.0",
    "nltk==3.9.1",
    "numpy==2.2.3",
    "openpyxl==3.1.5",
    "pandas==2.2.3",
    "tabulate==0.9.0",
    # "weasyprint==65.1",
]

[project.scripts]
otomasi = "otomasi.cli:main"
